spring:
  datasource:
    url: jdbc:postgresql://localhost:2731/postgres
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      enable_lazy_load_no_trans: true
    hibernate.ddl-auto: update

app:
  version: ${version}
  name: ${name}
