spring:
  datasource:
    url: jdbc:postgresql://kraksim-db.c1e5c3vhfdpy.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: zmien-na-haslo-prawdziwe
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      enable_lazy_load_no_trans: true
    hibernate.ddl-auto: update

app:
  version: ${version}
  name: ${name}
