name: Code quality review

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - run: brew install ktlint

      - name: "ktlint"
        id: klint-run
        run: echo "::set-output name=klint-output::$(ktlint)\n"

      - name: Execute tests
#        if: steps.klint-run.outcome == 'success' && steps.klint-run.conclusion == 'success'
        run: echo ${{steps.klint-run.outputs.klint-output}}